version: '3'

networks:
  java-net:
    driver: bridge

services:
  # kafka(choreography)
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - java-net
    container_name: zookeeperContainer
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - java-net
    container_name: kafkaContainer
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
